add_PyErr_SetFromErrnoWithFilenameObject_try_2
